name: CI

on:
  push:
  create:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create builddir
        run: mkdir target

      - name: Fill in version
        run: sed s/PLACEHOLDER/BLA/ test.xsd > target/test.xsd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/test.xsd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
