name: CI

on:
  push:
  create:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create builddir
        run: mkdir target

      - name: Fill in version
        run: ./create_artifact.sh

      - name: Store as release
        if: startswith(github.ref, "refs/tags/")
        uses: softprops/action-gh-release@v1
        with:
          files: target/artifact/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store as branch artifact
        if: startswith(github.ref, "refs/heads/")
        uses: actions/upload-artifact@v2
        with:
          name: branch-artifact
          path: |
            target/artifact/*

