name: CI

on:
  push:
  create:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install markdown-pdf
        run: npm install -g markdown-pdf --ignore-scripts

      - name: Convert markdown to pdf
        run: markdown-pdf test.md

#      - name: Create artifact
#        run: ./create_artifact.sh

#      - name: Store as release
#        if: ${{ startswith(github.ref, 'refs/tags/') }}
#        uses: softprops/action-gh-release@v1
#        with:
#          files: target/artifact/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Store as branch artifact
#        if: ${{ startswith(github.ref, 'refs/heads/') }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: branch-artifact
#          path: target/artifact/*.zip

